
const constants = {
    DEV_ENVIRONEMENT : 'development',
    COOKIE_NAME : 'session',
    ERROR_CODE_DUPLICATE : 'ERROR_CODE_DUPLICATE',
    ERROR_CODE_PASSWORD_DONT_MATCH : 'ERROR_CODE_PASSWORD_DONT_MATCH',
    ERROR_CODE_USER_DONT_MATCH: 'ERROR_CODE_USER_DONT_MATCH',

    ERROR_CODE_TOKEN_EXPIRED : 'ERROR_CODE_TOKEN_EXPIRED',
    ERROR_CODE_TOKEN_NOT_RECOGNIZED : 'ERROR_CODE_TOKEN_NOT_RECOGNIZED',
    MONGO_ERROR_DUPLICATE : 11000
}

module.exports = constants