
const constants = {
    DEV_ENVIRONEMENT : 'development',
    COOKIE_NAME : 'session',
    ERROR_CODE_DUPLICATE : 'ERROR_CODE_DUPLICATE',
    ERROR_CODE_PASSWORD_DONT_MATCH : 'ERROR_CODE_PASSWORD_DONT_MATCH',
    ERROR_CODE_USER_DONT_MATCH: 'ERROR_CODE_USER_DONT_MATCH',

    MONGO_ERROR_DUPLICATE : 11000
}

module.exports = constants